#!/bin/bash

currentPath=$(pwd)
url=$(wl-paste)
download_dir="$HOME/Downloads/videos"
mkdir -p "$download_dir"
cd "$download_dir" || exit

# Check for --audio argument
if [[ "$1" == "--audio" ]]; then
  yt-dlp -x --audio-format mp3 --audio-quality 0 "$url" -v -S "ext" "${@:2}"
else
  yt-dlp "$url" -v -S "ext" "$@"
fi

cd "$currentPath" || exit
